"""The public developer API: keys, rate limits, and two combined endpoints.

Public endpoints (documented on the site's /developers page):

    GET /api/packages                   list, with filters
    GET /api/packages/{id}              one package, with live route conditions
    GET /api/destinations               destinations with their safety score
    GET /api/conditions/{destination}   weather + earthquakes + road status + safety
    GET /api/restaurants?lat=&lng=      restaurants near a point

Anyone may call them. Without a key a caller gets 60 requests a minute per IP;
with an operator's key (`X-API-Key` header or `api_key` query parameter),
600 a minute per key. Every response carries X-RateLimit-* headers, and a
caller over the limit gets 429 with Retry-After.

Keys are generated by operators and admins from their dashboard. Only the
SHA-256 of a key is stored; the key itself is shown once.
"""
from __future__ import annotations

import hashlib
import secrets
import time
from collections import defaultdict, deque

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from pydantic import BaseModel, Field

from . import auth
from .db import records

router = APIRouter(tags=["developer"])

WINDOW_SEC = 60
LIMIT_ANON = 60
LIMIT_KEY = 600

_hits: dict[str, deque] = defaultdict(deque)


def _hash(key: str) -> str:
    return hashlib.sha256(key.encode()).hexdigest()


def client_ip(request: Request) -> str:
    fwd = request.headers.get("x-forwarded-for", "")
    return (fwd.split(",")[0].strip() if fwd else (request.client.host if request.client else "?"))


def _check(bucket: str, limit: int, response: Response) -> None:
    now = time.monotonic()
    q = _hits[bucket]
    while q and now - q[0] > WINDOW_SEC:
        q.popleft()
    remaining = limit - len(q)
    reset = int(WINDOW_SEC - (now - q[0])) + 1 if q else WINDOW_SEC
    response.headers["X-RateLimit-Limit"] = str(limit)
    if remaining <= 0:
        raise HTTPException(429, f"Rate limit of {limit} requests per minute exceeded",
                            headers={"Retry-After": str(reset), "X-RateLimit-Limit": str(limit),
                                     "X-RateLimit-Remaining": "0"})
    q.append(now)
    response.headers["X-RateLimit-Remaining"] = str(remaining - 1)
    response.headers["X-RateLimit-Reset"] = str(reset)


async def rate_limited(request: Request, response: Response) -> dict:
    """Dependency for public endpoints. Returns who the call is billed to."""
    key = request.headers.get("x-api-key") or request.query_params.get("api_key") or ""
    if key:
        row = await records.key_by_hash(_hash(key))
        if not row or row["revoked"]:
            raise HTTPException(401, "Invalid or revoked API key")
        _check("key:" + row["id"], LIMIT_KEY, response)
        await records.touch_key(row["id"])
        return {"key_id": row["id"], "limit": LIMIT_KEY}
    _check("ip:" + client_ip(request), LIMIT_ANON, response)
    return {"key_id": None, "limit": LIMIT_ANON}


def reset_limits() -> None:
    _hits.clear()


# ------------------------------------------------------------------- keys
class KeyIn(BaseModel):
    label: str = Field("My integration", min_length=1, max_length=80)


@router.get("/api/developer/keys")
async def my_keys(user: auth.Identity = Depends(auth.require_role("operator"))):
    return {"items": await records.keys(user.uid), "limits": {"anonymous": LIMIT_ANON, "with_key": LIMIT_KEY}}


@router.post("/api/developer/keys", status_code=201)
async def create_key(body: KeyIn, user: auth.Identity = Depends(auth.require_role("operator"))):
    active = [k for k in await records.keys(user.uid) if not k["revoked"]]
    if len(active) >= 5:
        raise HTTPException(409, "You already have 5 active keys — revoke one first.")
    key = "nt_" + secrets.token_urlsafe(32)
    row = await records.add_key({"id": secrets.token_hex(8), "uid": user.uid, "label": body.label.strip(),
                                 "prefix": key[:10], "key_hash": _hash(key)})
    return {**row, "key": key, "note": "Copy this key now — it is not shown again."}


@router.delete("/api/developer/keys/{key_id}")
async def revoke(key_id: str, user: auth.Identity = Depends(auth.require_role("operator"))):
    if not await records.revoke_key(user.uid, key_id):
        raise HTTPException(404, "No such key")
    return {"revoked": key_id}
